<script setup>
import { computed } from "vue";
import {
  AlignLeft,
  ArrowLeft,
  Archive,
  ArrowRight,
  ArrowUpDown,
  BarChart3,
  BookOpen,
  CalendarDays,
  CalendarSearch,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsUpDown,
  CircleHelp,
  CirclePlus,
  Clock3,
  Columns3,
  Download,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Folder,
  FolderPlus,
  GitCommitVertical,
  Hash,
  Image,
  LayoutGrid,
  LibraryBig,
  Link2,
  List,
  ListChecks,
  ListTree,
  Mail,
  Maximize2,
  Menu,
  Phone,
  SquareCheck,
  MoreHorizontal,
  MoreVertical,
  NotebookText,
  Paperclip,
  Pin,
  Plus,
  RotateCcw,
  Save,
  Search,
  Settings,
  SlidersHorizontal,
  SquarePen,
  SquareKanban,
  Star,
  Table2,
  Type,
  Leaf,
  Trash2,
  X,
} from "@lucide/vue";

const props = defineProps({
  name: {
    type: String,
    required: true,
  },
  strokeWidth: {
    type: Number,
    default: 1.8,
  },
});

const icons = {
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUpDown: ArrowUpDown,
  alignLeft: AlignLeft,
  archive: Archive,
  bar: BarChart3,
  book: BookOpen,
  calendar: CalendarDays,
  calendarSearch: CalendarSearch,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronsUpDown: ChevronsUpDown,
  close: X,
  clock: Clock3,
  columns: Columns3,
  download: Download,
  edit: SquarePen,
  eye: Eye,
  eyeOff: EyeOff,
  file: FileText,
  filter: Filter,
  fold: ChevronsDownUp,
  unfold: ChevronsUpDown,
  folder: Folder,
  folderPlus: FolderPlus,
  hash: Hash,
  help: CircleHelp,
  image: Image,
  gallery: LayoutGrid,
  library: LibraryBig,
  leaf: Leaf,
  link: Link2,
  list: List,
  listChecks: ListChecks,
  outline: ListTree,
  checkSquare: SquareCheck,
  mail: Mail,
  phone: Phone,
  maximize: Maximize2,
  menu: Menu,
  more: MoreHorizontal,
  moreVertical: MoreVertical,
  note: NotebookText,
  notebook: NotebookText,
  paperclip: Paperclip,
  pin: Pin,
  plus: CirclePlus,
  plusCircle: CirclePlus,
  plusSign: Plus,
  restore: RotateCcw,
  save: Save,
  search: Search,
  settings: Settings,
  sliders: SlidersHorizontal,
  squarePen: SquarePen,
  board: SquareKanban,
  star: Star,
  table: Table2,
  timeline: GitCommitVertical,
  trash: Trash2,
  type: Type,
};

const icon = computed(() => icons[props.name] || MoreHorizontal);
</script>

<template>
  <component
    :is="icon"
    class="timeline-lucide-icon"
    aria-hidden="true"
    focusable="false"
    :stroke-width="props.strokeWidth"
  />
</template>
