<script setup>
import { computed } from "vue";
import {
  AArrowDown,
  AArrowUp,
  AlignLeft,
  ArrowLeft,
  Archive,
  ArrowRight,
  ArrowUpDown,
  BarChart3,
  BookOpen,
  CalendarDays,
  CalendarSearch,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsUpDown,
  CircleHelp,
  CirclePlus,
  Clock3,
  Columns3,
  Download,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flag,
  Folder,
  FolderPlus,
  GitCommitVertical,
  Hash,
  Heart,
  Image,
  Info,
  LayoutGrid,
  Lightbulb,
  LibraryBig,
  Link2,
  List,
  ListChecks,
  ListTree,
  Mail,
  Maximize2,
  Menu,
  Minimize2,
  Network,
  Phone,
  SquareCheck,
  MoreHorizontal,
  MoreVertical,
  NotebookText,
  Paperclip,
  Pin,
  Plus,
  RotateCcw,
  Save,
  Search,
  Settings,
  SlidersHorizontal,
  SquarePen,
  SquareKanban,
  Star,
  Table2,
  Tag,
  TriangleAlert,
  Type,
  Leaf,
  Trash2,
  Bold,
  PaintBucket,
  Palette,
  Redo2,
  Undo2,
  Workflow,
  X,
} from "@lucide/vue";

const props = defineProps({
  name: {
    type: String,
    required: true,
  },
  strokeWidth: {
    type: Number,
    default: 1.5,
  },
});

const icons = {
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUpDown: ArrowUpDown,
  alignLeft: AlignLeft,
  archive: Archive,
  bar: BarChart3,
  book: BookOpen,
  calendar: CalendarDays,
  calendarSearch: CalendarSearch,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronsUpDown: ChevronsUpDown,
  close: X,
  clock: Clock3,
  columns: Columns3,
  download: Download,
  edit: SquarePen,
  eye: Eye,
  eyeOff: EyeOff,
  file: FileText,
  filter: Filter,
  flag: Flag,
  fold: ChevronsDownUp,
  unfold: ChevronsUpDown,
  folder: Folder,
  folderPlus: FolderPlus,
  hash: Hash,
  heart: Heart,
  help: CircleHelp,
  idea: Lightbulb,
  image: Image,
  info: Info,
  gallery: LayoutGrid,
  library: LibraryBig,
  leaf: Leaf,
  link: Link2,
  list: List,
  listChecks: ListChecks,
  outline: ListTree,
  checkSquare: SquareCheck,
  mail: Mail,
  phone: Phone,
  maximize: Maximize2,
  minimize: Minimize2,
  mindmap: Network,
  undo: Undo2,
  redo: Redo2,
  bold: Bold,
  fontDown: AArrowDown,
  fontUp: AArrowUp,
  palette: Palette,
  paint: PaintBucket,
  layout: Workflow,
  menu: Menu,
  more: MoreHorizontal,
  moreVertical: MoreVertical,
  note: NotebookText,
  notebook: NotebookText,
  paperclip: Paperclip,
  pin: Pin,
  plus: CirclePlus,
  plusCircle: CirclePlus,
  plusSign: Plus,
  restore: RotateCcw,
  save: Save,
  search: Search,
  settings: Settings,
  sliders: SlidersHorizontal,
  squarePen: SquarePen,
  board: SquareKanban,
  star: Star,
  table: Table2,
  tag: Tag,
  alert: TriangleAlert,
  timeline: GitCommitVertical,
  trash: Trash2,
  type: Type,
};

const icon = computed(() => icons[props.name] || MoreHorizontal);
</script>

<template>
  <component
    :is="icon"
    class="timeline-lucide-icon"
    aria-hidden="true"
    focusable="false"
    :stroke-width="props.strokeWidth"
  />
</template>
